---

- name: delete instance(s)
  gcp_compute_instance:
    project: "{{ project_id }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ credentials_file }}"
    name: "{{ gce_prefix }}-{{ item.name }}"
    zone: "{{ gce_zone }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: absent
  async: 7200
  poll: 0
  register: deploy
  loop: "{{ disks }}"
  when: disks is defined

- name: wait for instance deletion to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: instances
  until: instances.finished
  retries: "{{ instance_wait_retry_limit }}"
  delay: 10
  loop: "{{ deploy.results }}"